### ISSUE TITLE
Images copied from a Word document fail to be included

### ISSUE THREAD

**Issue by avernet** [pangaeatech/tinymce-paste-from-word-plugin#125]
With Chrome, the following error shows on the console:

> Not allowed to load local resource: file:///Users/avernet/Library/Group%20Containers/XYZ.Office/TemporaryItems/msohtmlclip/clip_image001.jpg

I'm not sure if pasting images is supported by this plugin. If not, and if supporting images is considered out of scope for this plugin, this might be worth mentioning in the `README.md`.

**Comment by mwaddell** [comment]
Supporting images is out of scope for this plugin.  I have added a comparison table to the README.  

Thank you for the feedback.
