### ISSUE TITLE
Review and Test prior to publicizing project

### ISSUE THREAD

**Issue by mwaddell** [pangaeatech/tinymce-paste-from-word-plugin#17]
I pulled the "Paste from Word" functionality out of the 5.x branch of TinyMCE and dumped it (virtually unchanged other than stripping out all the extraneous stuff and updating it to be compatible with 6.x) into this project and published it as 2 different packages to NPM.

I created a README explaining the 3 different ways to use the plugin and the different settings that impact its usage.

Before I reach out to the TinyMCE group to let them know we're willing to maintain this, I want someone (other than me) to do the following:

- [x] Review the README.md to make sure it reads clearly and all the links are valid.
- [ ] Find/Create a Word Document whose contents can be used for testing this plugin (e.g. it pastes wrong in TinyMCE 6.x without this plugin but works with the plugin - all other settings being the same.)
    - Note: the easiest way to test this is with nested numbered/bulleted lists.  Without the paste_from_word plugin, they paste as plain styled text, but with the paste_from_word plugin, they paste as actual bullet/numbered lists so you can easily modify them after pasting.
- [ ] Test each of the 3 usage options in the README to make sure they work correctly and I didn't leave any details out (test them using the word document noted above)
- [ ] Review the other files in this repo to make sure I didn't miss anything we should add/include.

**Comment by jfbelanger-rruq** [comment]
I used your plugin in Umbraco CMS (they upgraded from TinyMCE 4 to 6 in the last release Umbraco 13... so Word paste where less than optimal)

The readme file is good, every is clear and every link works as expected.

I used only the Option 2, local hosting, placed the file in "umbraco\lib\tinymce\plugins\paste_from_word" and added the config in the Umbraco appsettings.json:
  "Umbraco": {
    "CMS": {
	  "RichTextEditor": {
			"Plugins": ["paste_from_word"],
			"paste_webkit_styles": "all",
			"paste_remove_styles_if_webkit": false,			
      },	
It work great, pasted a few word document with formating and list and it works as it used to in Umbraco 8. 

(Added the step to configure the plugin in Umbraco to help those who will find your repo, when searching for why this don't work anymore in Umbraco)

Thanks

**Comment by mwaddell** [comment]
Given the change of TinyMCE from LGPL/MIT to GPLv2 with v7.x - this project will become read-only when v6.x support ends in October 2024, so there is no longer any need to publicize it.

**Comment by mwaddell** [comment]
See also https://github.com/tinymce/tinymce/discussions/8539#discussioncomment-10260158
